export const UPDATE_GAMES = `UPDATE_GAMES`
export const TYPES = {
  AFFENPINSCHER: 'AFFENPINSCHER',
  AIREDALE: 'AIREDALE',
  AKITA: 'AKITA',
  BASENJI: 'BASENJI',
  BEAGLE: 'BEAGLE',
  BLUETICK: 'BLUETICK',
  BORZOI: 'BORZOI',
  BOUVIER: 'BOUVIER',
  CAIRN: 'CAIRN',
  CHIHUAHUA: 'CHIHUAHUA',
  CARDIGAN_CORGI: 'CARDIGAN CORGI',
  DHOLE: 'DHOLE',
  DINGO: 'DINGO',
  DOBERMAN: 'DOBERMAN',
}
